/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daniel Lima
 */
public class AdmGUI extends javax.swing.JFrame {
    CadastroUsuarioGUI cadastroUsuarioGUI;
    CadastroProdutoGUI cadastroProdutoGUI;
    CadastroIngredientesGUI cadastroIngredientesGUI;
    CadastroReceitaGUI cadastroReceitaGUI;
    CadastroIngredienteDaReceitaGUI cadastroIngredienteDaReceitaGUI;
    CadastroEstoqueGUI cadastroEstoqueGUI;
    CadastroClientesGUI cadastroClientesGUI;
    CadastroVendaGUI cadastroVendaGUI;
    ListarVendasPeriodoGUI listarVendasPeriodoGUI;
    ListaProdutosProducaoGUI listaProdutosProducaoGUI;
    EntregaVendaGUI entregaVendaGUI;
    /**
     * Creates new form CadastroUsuarios
     */
    public AdmGUI() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGestao = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        menuGerencial = new javax.swing.JMenu();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenuIngrediente = new javax.swing.JMenuItem();
        jMenuIngredienteDaReceita = new javax.swing.JMenuItem();
        jMenuReceita = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenuItem();
        jMenuVendasPeriodo = new javax.swing.JMenuItem();
        menuCaixa = new javax.swing.JMenu();
        jMenuVendas = new javax.swing.JMenuItem();
        menuCozinha = new javax.swing.JMenu();
        jMenuProdutosProducao = new javax.swing.JMenuItem();
        jMenuEntregaVenda = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Restaurante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuGestao.setText("Modulo de Gestao");

        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsuarioMouseClicked(evt);
            }
        });
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        menuGestao.add(jMenuUsuario);

        jMenuCliente.setText("Clientes");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        menuGestao.add(jMenuCliente);

        jMenuBar1.add(menuGestao);

        menuGerencial.setText("Modulo Gerencial");

        jMenuProduto.setText("Produto");
        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuProduto);

        jMenuIngrediente.setText("Ingrediente");
        jMenuIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngredienteActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuIngrediente);

        jMenuIngredienteDaReceita.setText("Ingredientes da Receita");
        jMenuIngredienteDaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngredienteDaReceitaActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuIngredienteDaReceita);

        jMenuReceita.setText("Receita");
        jMenuReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReceitaActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuReceita);

        jMenuEstoque.setText("Estoque de Ingredientes");
        jMenuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstoqueActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuEstoque);

        jMenuVendasPeriodo.setText("Vendas por Período");
        jMenuVendasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasPeriodoActionPerformed(evt);
            }
        });
        menuGerencial.add(jMenuVendasPeriodo);

        jMenuBar1.add(menuGerencial);

        menuCaixa.setText("Modulo Frente Caixa");

        jMenuVendas.setText("Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });
        menuCaixa.add(jMenuVendas);

        jMenuBar1.add(menuCaixa);

        menuCozinha.setText("Modulo Cozinha");

        jMenuProdutosProducao.setText("Produtos em Produção");
        jMenuProdutosProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutosProducaoActionPerformed(evt);
            }
        });
        menuCozinha.add(jMenuProdutosProducao);

        jMenuEntregaVenda.setText("Entrega da Venda");
        jMenuEntregaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEntregaVendaActionPerformed(evt);
            }
        });
        menuCozinha.add(jMenuEntregaVenda);

        jMenuBar1.add(menuCozinha);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
           
            if(cadastroUsuarioGUI == null){
                  cadastroUsuarioGUI = new CadastroUsuarioGUI();
              }
                    cadastroUsuarioGUI.setVisible(true);
                    cadastroUsuarioGUI.setExtendedState(NORMAL);
                    cadastroUsuarioGUI.limpaCampos();
                    cadastroUsuarioGUI.limparUsuTable();
                    
    }//GEN-LAST:event_jMenuUsuarioActionPerformed
    
    private void jMenuIngredienteDaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngredienteDaReceitaActionPerformed
        if( cadastroIngredienteDaReceitaGUI == null){
            try {
                cadastroIngredienteDaReceitaGUI = new CadastroIngredienteDaReceitaGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    cadastroIngredienteDaReceitaGUI.setVisible(true);
                    cadastroIngredienteDaReceitaGUI.setExtendedState(NORMAL);
                    cadastroIngredienteDaReceitaGUI.limpaCampos();
        try {
            cadastroIngredienteDaReceitaGUI.inicializaComboIngrediente();
            cadastroIngredienteDaReceitaGUI.inicializaComboReceita();
            cadastroIngredienteDaReceitaGUI.inicializaComboReceitaConsulta();
            cadastroIngredienteDaReceitaGUI.limparIngDaReceitaTable();
            
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
    }//GEN-LAST:event_jMenuIngredienteDaReceitaActionPerformed

    private void jMenuIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngredienteActionPerformed
        if(cadastroIngredientesGUI == null){
            try {
                cadastroIngredientesGUI = new CadastroIngredientesGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    cadastroIngredientesGUI.setVisible(true);
                    cadastroIngredientesGUI.setExtendedState(NORMAL);
                    cadastroIngredientesGUI.limpaCampos();
        try {
            cadastroIngredientesGUI.inicializaComboIngrediente();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuIngredienteActionPerformed

    private void jMenuReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReceitaActionPerformed
        if(cadastroReceitaGUI == null){
            try {
                cadastroReceitaGUI = new CadastroReceitaGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    cadastroReceitaGUI.setVisible(true);
                    cadastroReceitaGUI.setExtendedState(NORMAL);
                    cadastroReceitaGUI.limparCampos();
        try {
            cadastroReceitaGUI.inicializaComboReceita();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuReceitaActionPerformed

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
       if(cadastroProdutoGUI == null){
            try {
                cadastroProdutoGUI = new CadastroProdutoGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    cadastroProdutoGUI.setVisible(true);
                    cadastroProdutoGUI.setExtendedState(NORMAL);
        try {
            cadastroProdutoGUI.inicializaComboReceita();
            cadastroProdutoGUI.inicializaComboProduto();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                    cadastroProdutoGUI.limparCampos();
    }//GEN-LAST:event_jMenuProdutoActionPerformed
    
    private void jMenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuarioMouseClicked
        
    }//GEN-LAST:event_jMenuUsuarioMouseClicked

    private void jMenuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstoqueActionPerformed
        if( cadastroEstoqueGUI == null){
            try {
                cadastroEstoqueGUI = new CadastroEstoqueGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    cadastroEstoqueGUI.setVisible(true);
                    cadastroEstoqueGUI.setExtendedState(NORMAL);
                    cadastroEstoqueGUI.limpaCampos();
        try {
            cadastroEstoqueGUI.inicializaComboIngrediente();
            cadastroEstoqueGUI.inicializaComboEstoque();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_jMenuEstoqueActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
       if( cadastroClientesGUI == null){
           try {
               cadastroClientesGUI = new CadastroClientesGUI();
           } catch (Exception ex) {
               Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
              }     
                    cadastroClientesGUI.setVisible(true);
                    cadastroClientesGUI.setExtendedState(NORMAL);
                    cadastroClientesGUI.limpaCampos();
        try {
            cadastroClientesGUI.inicializaComboCliente();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuVendasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasPeriodoActionPerformed
       if(listarVendasPeriodoGUI == null){
            try {
                listarVendasPeriodoGUI = new ListarVendasPeriodoGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    listarVendasPeriodoGUI.setVisible(true);
                    listarVendasPeriodoGUI.setExtendedState(NORMAL);
                    listarVendasPeriodoGUI.limparVendaTable();
                    listarVendasPeriodoGUI.limparProdTable();
                    listarVendasPeriodoGUI.limpaCampos();    
                    
    }//GEN-LAST:event_jMenuVendasPeriodoActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
         if( cadastroVendaGUI == null){
            try {
                cadastroVendaGUI = new CadastroVendaGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                    cadastroVendaGUI.setVisible(true);
                    cadastroVendaGUI.setExtendedState(NORMAL);
                    cadastroVendaGUI.limpaCampos();
                    cadastroVendaGUI.limparProdTable();
        try {
            cadastroVendaGUI.inicializaComboCliente();
            cadastroVendaGUI.inicializaComboConsultaVenda();
            cadastroVendaGUI.inicializaComboProduto();
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                   
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuProdutosProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutosProducaoActionPerformed
        if(listaProdutosProducaoGUI == null){
            try {
                listaProdutosProducaoGUI = new ListaProdutosProducaoGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    listaProdutosProducaoGUI.setVisible(true);
                    listaProdutosProducaoGUI.setExtendedState(NORMAL);
                    listaProdutosProducaoGUI.limparProdTable();
                    listaProdutosProducaoGUI.limpaCampos(); 
                    
    }//GEN-LAST:event_jMenuProdutosProducaoActionPerformed

    private void jMenuEntregaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEntregaVendaActionPerformed
        if(entregaVendaGUI == null){
            try {
                entregaVendaGUI = new EntregaVendaGUI();
            } catch (Exception ex) {
                Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
                    entregaVendaGUI.setVisible(true);
                    entregaVendaGUI.setExtendedState(NORMAL);
                    entregaVendaGUI.limparProdTable();
                    entregaVendaGUI.limpaCampos();    
        try {
            entregaVendaGUI.inicializaComboConsultaVenda();
            
        } catch (Exception ex) {
            Logger.getLogger(AdmGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuEntregaVendaActionPerformed
    public void desabilitaGerente(){
        menuCaixa.setVisible(false);
        menuCozinha.setVisible(false);
        menuGestao.setVisible(false);
    }
    public void desabilitaCaixa(){
        menuGerencial.setVisible(false);
        menuCozinha.setVisible(false);
        menuGestao.setVisible(false);
    }
    public void desabilitaCozinha(){
        menuCaixa.setVisible(false);
        menuGerencial.setVisible(false);
        menuGestao.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                AdmGUI admGUI = new AdmGUI();
                admGUI.setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuEntregaVenda;
    private javax.swing.JMenuItem jMenuEstoque;
    private javax.swing.JMenuItem jMenuIngrediente;
    private javax.swing.JMenuItem jMenuIngredienteDaReceita;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenuItem jMenuProdutosProducao;
    private javax.swing.JMenuItem jMenuReceita;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JMenuItem jMenuVendasPeriodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenu menuCozinha;
    private javax.swing.JMenu menuGerencial;
    private javax.swing.JMenu menuGestao;
    // End of variables declaration//GEN-END:variables
}
