/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;



import dao.EstoqueDAO;
import dao.IngredienteDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.text.DateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Estoque;
import model.Ingrediente;
import util.Data.ValidaData;
import util.ValidaNumeros;

/**
 *
 * @author Daniel Lima
 */
public class CadastroEstoqueGUI extends javax.swing.JFrame {
    Ingrediente ing;
    IngredienteDAO ingDAO;
    Estoque est;
    EstoqueDAO estDAO;
    ValidaData validaData;
    private List<Ingrediente> ingredientes = new ArrayList<>();
    private List<Ingrediente> ingredienteEstoque = new ArrayList<>();
    private List<Estoque> estoque = new ArrayList<>();
    /**
     * Creates new form CadastroEstoqueGUI
     */
    public CadastroEstoqueGUI() throws Exception {
        initComponents();
        txtQntd.setDocument(new ValidaNumeros());
        txtNumeroLote.setDocument(new ValidaNumeros());
        inicializaComboIngrediente();
        inicializaComboEstoque();
        //colocar a funçao de verificar os numeros aki
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIngredientes = new javax.swing.JLabel();
        cbIngredienteEstoque = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIngrediente = new javax.swing.JLabel();
        cbIngrediente = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        txtQntd = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDataValidade = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroLote = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque de Ingredientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lblIngredientes.setText("Estoque");

        cbIngredienteEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIngredienteEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredienteEstoqueActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngredientes)
                .addGap(31, 31, 31)
                .addComponent(cbIngredienteEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngredientes)
                    .addComponent(cbIngredienteEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        lblIngrediente.setText("Ingrediente");

        cbIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredienteActionPerformed(evt);
            }
        });

        lblQuantidade.setText("Quantidade");

        txtQntd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQntdFocusGained(evt);
            }
        });
        txtQntd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntdActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel1.setText("Data de Validade");

        try {
            txtDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataValidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataValidadeFocusLost(evt);
            }
        });
        txtDataValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataValidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Número Lote");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQuantidade)
                            .addComponent(lblIngrediente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIngrediente, 0, 176, Short.MAX_VALUE)
                            .addComponent(txtQntd)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(23, 23, 23))
                            .addComponent(txtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnLimpar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIngrediente)
                            .addComponent(cbIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnAtualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQntdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntdActionPerformed

    private void cbIngredienteEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredienteEstoqueActionPerformed
            //defineIdsEstoque();
            //System.out.println("" + est.getIdEstoque());
    }//GEN-LAST:event_cbIngredienteEstoqueActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(cbIngrediente.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um Ingrediente para Cadastro !");
        }
       else{

        if(txtQntd.getText().equals("") || txtNumeroLote.getText().equals("") || txtDataValidade.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null,"Campos vazios!!");
        }else{
        ing = new Ingrediente();
        est = new Estoque();
        
        try {
            defineIdsIngrediente();
            //System.out.println("" + ing.getIdIngrediente());
            est.setQtdEstoque(Integer.parseInt(txtQntd.getText()));
            
            //Transformando String para sql.Date
            String dataString = txtDataValidade.getText();
            
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataValidadeTemp = new java.sql.Date(fmt.parse(dataString).getTime());
            
            est.setDataVencimentoEstoque(dataValidadeTemp);
            est.setNumeroLoteEstoque(txtNumeroLote.getText());
            
            estDAO = new EstoqueDAO();
           
            estDAO.cadastrar(est,ing.getIdIngrediente());
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
            //System.out.println("aki");
            inicializaComboEstoque();
            limpaCampos();
        } catch (Exception ex) {
            Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredienteActionPerformed
        //defineIdsIngrediente();
        //System.out.println("" + ing.getIdIngrediente());
    }//GEN-LAST:event_cbIngredienteActionPerformed

    private void txtDataValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataValidadeActionPerformed
       
               
    }//GEN-LAST:event_txtDataValidadeActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

            limpaCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtQntdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQntdFocusGained
        
        
    }//GEN-LAST:event_txtQntdFocusGained

    private void txtDataValidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataValidadeFocusLost
           if(!txtDataValidade.getText().equals("  /  /    ")){
              if(!ValidaData.validaData(txtDataValidade.getText())){
                  JOptionPane.showMessageDialog(null,"Data invalida");
                  txtDataValidade.setText("");
                  txtDataValidade.requestFocus();
                //  System.out.println("" + txtDataValidade.getText()); 
              }
           }
           
    }//GEN-LAST:event_txtDataValidadeFocusLost

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         if(cbIngredienteEstoque.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Selecione um Item no Estoque!");
        }else{
            try {
                est = new Estoque();
                ing = new Ingrediente();
                defineIdsEstoque();
                estDAO = new EstoqueDAO();
                //System.out.println("" + ing.getIdIngrediente());
                estDAO.pesquisar(est,ing);
                  txtQntd.setText(est.getQtdEstoque()+"");
                  txtNumeroLote.setText(est.getNumeroLoteEstoque());
                  SimpleDateFormat formatdata = new SimpleDateFormat("dd/MM/yyyy");
                  txtDataValidade.setText(formatdata.format(est.getDataVencimentoEstoque()));
                  
                  //txtDataValidade.setText();
//                txtNome.setText(cli.getNomeCliente());
//                txtSobreNome.setText(cli.getSobreNomeCliente());
//                txtCpf.setText(cli.getCpfCliente());
            } catch (Exception ex) {
                Logger.getLogger(CadastroClientesGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(cbIngredienteEstoque.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um Ingrediente para Cadastro !");
        }
//        else{
//        }
        if(txtQntd.getText().equals("") || txtNumeroLote.getText().equals("") || txtDataValidade.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Campos vazios!!");
        }else{
        est = new Estoque();
        defineIdsEstoque();
        try {
            est.setIdEstoque(est.getIdEstoque());
            est.setQtdEstoque(Integer.parseInt(txtQntd.getText()));
            est.setNumeroLoteEstoque(txtNumeroLote.getText());
            
            String dataString2 = txtDataValidade.getText();
            
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataValidadeTemp2 = new java.sql.Date(fmt.parse(dataString2).getTime());
            
            est.setDataVencimentoEstoque(dataValidadeTemp2);
            estDAO = new EstoqueDAO();
            estDAO.atualizar(est);
                JOptionPane.showMessageDialog(null,"Item do estoque alterado com sucesso!");
            inicializaComboEstoque();
            
            limpaCampos();
        } catch (Exception ex) {
            Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(cbIngredienteEstoque.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(null,"Selecione um ingrediente no combo de estoque!");
        }else{
        est = new Estoque();
        try {
            int opcao =  JOptionPane.showConfirmDialog(null,"Pode haver Produto com esse Ingrediente deseja realmente excluir?");
                  if(opcao == 0){
            estDAO = new EstoqueDAO();
            defineIdsEstoque();
            
            //est.setIdEstoque();
            //System.out.println("" + est.getIdEstoque());
            estDAO.excluir(est);
            JOptionPane.showMessageDialog(null,"Ingrediente excluido do estoque!!");
            inicializaComboEstoque();
            }
            
            
            } catch (Exception ex) {
                Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try {
            inicializaComboIngrediente();
            inicializaComboEstoque();
        } catch (Exception ex) {
            Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnAtualizarActionPerformed
public final void inicializaComboEstoque() throws Exception {
        DefaultComboBoxModel comboEstoque = new DefaultComboBoxModel();
        comboEstoque.addElement("Selecione Ingrediente do Estoque");
        
        //est = new Estoque();
        estDAO = new EstoqueDAO();
        ing = new Ingrediente();
        estoque = estDAO.listaTodoEstoque(); //ingDAO.listaTodosIngredientes(ing);
        
        for(Estoque e: estoque){
            ingDAO = new IngredienteDAO();
            //System.out.println(e.getIdIngrediente());
            ingredienteEstoque = ingDAO.consultaTodosIngredientes(e.getIdIngrediente());
            for(Ingrediente i: ingredienteEstoque){
                //System.out.println("aki");
                //System.out.println(i.getNomeIngrediente());
                comboEstoque.addElement("Nome " + i.getNomeIngrediente() + " Lote " + e.getNumeroLoteEstoque());
            }
        }
        
        cbIngredienteEstoque.setModel(comboEstoque);
        
        //cbIngrediente.setSelectedIndex(0);
    }
public final void inicializaComboIngrediente() throws Exception {
        DefaultComboBoxModel comboIngrediente = new DefaultComboBoxModel();
        comboIngrediente.addElement("Selecione Ingrediente");
        ingDAO = new IngredienteDAO();
        ing = new Ingrediente();
        ingredientes = ingDAO.listaTodosIngredientes(ing);
        for (Ingrediente i : ingredientes) {
            comboIngrediente.addElement("ID " + i.getIdIngrediente() + " " +i.getNomeIngrediente());
        }
        cbIngrediente.setModel(comboIngrediente);
        
        //cbIngrediente.setSelectedIndex(0);
    }
   private void defineIdsIngrediente(){
     int ind = cbIngrediente.getSelectedIndex();
        if (ind < 1) {
            ing = null;
            return;
        }
        ind--;
        ing = ingredientes.get(ind);
        //System.out.println(rece.getIdReceita());
    }
    private void defineIdsEstoque(){
     int ind = cbIngredienteEstoque.getSelectedIndex();
        if (ind < 1) {
            est = null;
            return;
        }
        ind--;
        est = estoque.get(ind);
        //System.out.println(rece.getIdReceita());
    }
    public void limpaCampos(){
        txtQntd.setText("");
        txtDataValidade.setText("");
        txtNumeroLote.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               
//                CadastroEstoqueGUI cadastroEstoqueGUI = new CadastroEstoqueGUI();
//                try {
//                    cadastroEstoqueGUI.setVisible(true);
//                    cadastroEstoqueGUI.inicializaComboIngrediente();
//                    cadastroEstoqueGUI.inicializaComboEstoque();
//                     
//                } catch (Exception ex) {
//                    Logger.getLogger(CadastroEstoqueGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbIngrediente;
    private javax.swing.JComboBox<String> cbIngredienteEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JFormattedTextField txtDataValidade;
    private javax.swing.JTextField txtNumeroLote;
    private javax.swing.JTextField txtQntd;
    // End of variables declaration//GEN-END:variables
}
