/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.IngredienteDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.event.PrintJobEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Ingrediente;
import util.ValidaNumeros;

/**
 *
 * @author Daniel Lima
 */
public class CadastroIngredientesGUI extends javax.swing.JFrame {
     Ingrediente ingrediente;
     IngredienteDAO ingredienteDAO;
     private List<Ingrediente> ingredientes = new ArrayList<>();
    /**
     * Creates new form CadastroIngredientesGUI
     */
    public CadastroIngredientesGUI() throws Exception {
        initComponents();
        inicializaComboIngrediente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIngrediente = new javax.swing.JLabel();
        cbIngrediente = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtNomeIng = new javax.swing.JTextField();
        txtPrecoIng = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Ingredientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lblIngrediente.setText("Ingrediente");

        cbIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngredienteActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngrediente)
                .addGap(18, 18, 18)
                .addComponent(cbIngrediente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediente)
                    .addComponent(cbIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));
        jPanel2.setToolTipText("");

        lblNome.setText("Nome");

        lblPreco.setText("Preço");

        txtNomeIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeIngActionPerformed(evt);
            }
        });

        txtPrecoIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoIngActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblPreco))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeIng, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoIng, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         if(cbIngrediente.getSelectedIndex() == 0){
          JOptionPane.showMessageDialog(null,"Selecione um Ingrediente");
        }else{
        try {
            ingrediente = new Ingrediente();
            defineIdsIngrediente();
            ingredienteDAO = new IngredienteDAO();
            ingredienteDAO.pesquisar(ingrediente);
           
            txtNomeIng.setText(ingrediente.getNomeIngrediente());
            txtPrecoIng.setText(ingrediente.getPrecoIngrediente().toString());
            
        } catch (Exception ex) {
            Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeIngActionPerformed
       String nomeIngrediente = txtNomeIng.getText();
    }//GEN-LAST:event_txtNomeIngActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if("".equals(txtNomeIng.getText()) || "".equals(txtPrecoIng.getText())){
            JOptionPane.showMessageDialog(null,"Campo vazio !");
            }else{
         try {
             ingrediente = new Ingrediente();
             ingredienteDAO = new IngredienteDAO();
             ingrediente.setNomeIngrediente(txtNomeIng.getText());
             ingrediente.setPrecoIngrediente(Double.parseDouble(txtPrecoIng.getText()));
             ingredienteDAO.Cadastrar(ingrediente);
             
             JOptionPane.showMessageDialog(null,"Ingrediente Cadastrado !");
             inicializaComboIngrediente();
            } catch (Exception ex) {
             Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
           }
        limpaCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtPrecoIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoIngActionPerformed
        double precoIngrediente = Double.parseDouble(txtPrecoIng.getText());
    }//GEN-LAST:event_txtPrecoIngActionPerformed

    private void cbIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngredienteActionPerformed
       // System.out.println(cbIngrediente.getSelectedItem().toString());
        defineIdsIngrediente();
    }//GEN-LAST:event_cbIngredienteActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         if(cbIngrediente.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(null,"Selecione um Ingrediente!");
         }else{
         try {
             if("".equals(txtNomeIng.getText()) || "".equals(txtPrecoIng.getText())){
                    JOptionPane.showMessageDialog(null,"Campos Vazios");
                }else{
             ingredienteDAO = new IngredienteDAO();
             ingrediente = new Ingrediente();
             ingrediente.setIdIngrediente(cbIngrediente.getSelectedIndex());
             ingrediente.setNomeIngrediente(txtNomeIng.getText());
             ingrediente.setPrecoIngrediente(Double.parseDouble(txtPrecoIng.getText()));
             //System.out.println("" + ingrediente.getIdIngrediente());
             ingredienteDAO.atualizar(ingrediente);
             JOptionPane.showMessageDialog(null,"Ingrediente Alterado com sucesso!");
             inicializaComboIngrediente();
             limpaCampos();
                 }
         } catch (Exception ex) {
             Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(Level.SEVERE, null, ex);
         }
       }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(cbIngrediente.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um ingrediente!");
        }else{
           
            try {
                ingrediente = new Ingrediente();
                ingredienteDAO = new IngredienteDAO();
                int opcao =  JOptionPane.showConfirmDialog(null,"Esse ingrediente pode estar cadastrado no estoque deseja realmente excluir ?");
                    if(opcao == 0){
                ingrediente.setNomeIngrediente(cbIngrediente.getSelectedItem().toString());
                ingredienteDAO.excluir(ingrediente);
                 JOptionPane.showMessageDialog(null,"Ingrediente excluido!!");
                inicializaComboIngrediente();
                    }
               
            } catch (Exception ex) {
                Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
          
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
 public final void inicializaComboIngrediente() throws Exception {
        DefaultComboBoxModel comboIngrediente = new DefaultComboBoxModel();
        comboIngrediente.addElement("Selecione Ingrediente");
        ingredienteDAO = new IngredienteDAO();
        ingrediente = new Ingrediente();
        ingredientes = ingredienteDAO.listaTodosIngredientes(ingrediente);
        for (Ingrediente i : ingredientes) {
            comboIngrediente.addElement(i.getNomeIngrediente());
        }
        cbIngrediente.setModel(comboIngrediente);
        //cbIngrediente.setSelectedIndex(0);
    }
   private void defineIdsIngrediente(){
     int ind = cbIngrediente.getSelectedIndex();
        if (ind < 1) {
            ingrediente = null;
            return;
        }
        ind--;
        ingrediente = ingredientes.get(ind);
        //System.out.println(rece.getIdReceita());
    }
   public void limpaCampos(){
       txtNomeIng.setText("");
       txtPrecoIng.setText("");
       
   }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroIngredientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new CadastroIngredientesGUI().setVisible(true);
//               
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbIngrediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JTextField txtNomeIng;
    private javax.swing.JTextField txtPrecoIng;
    // End of variables declaration//GEN-END:variables
}
