/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author Daniel Lima
 */
public class CadastroClientesGUI extends javax.swing.JFrame {
    
    Cliente cli;
    ClienteDAO cliDAO;
    private List<Cliente> clientes = new ArrayList<>();
    
    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientesGUI() throws Exception {
        initComponents();
        inicializaComboCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNomeCad = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobreNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        lblNomeCad.setText("Nome");

        lblSobrenome.setText("SobreNome");

        lblCpf.setText("CPF");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCpf)
                            .addComponent(lblSobrenome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSobreNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNomeCad)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCad)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobrenome)
                    .addComponent(txtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lblNome.setText("Nome");

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Cliente" }));
        cbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNome)
                .addGap(30, 30, 30)
                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       if("".equals(txtNome.getText()) || "".equals(txtSobreNome.getText()) || "".equals(txtCpf.getText())){
            JOptionPane.showMessageDialog(null,"Campos vazios !");
        }else{
        
        Cliente cli = new Cliente();
        try {
            ClienteDAO cliDAO = new ClienteDAO();
            cli.setNomeCliente(txtNome.getText());
            cli.setSobreNomeCliente(txtSobreNome.getText());
            cli.setCpfCliente(txtCpf.getText());
            //System.out.println("" + cli.getCpfCliente());
            cliDAO.salvar(cli);
        } catch (Exception ex) {
            Logger.getLogger(CadastroReceitaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Cliente Cadastrada com Sucesso");
        
        try {
            inicializaComboCliente();
            limpaCampos();
        } catch (Exception ex) {
            Logger.getLogger(CadastroReceitaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
      
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesActionPerformed
        
    }//GEN-LAST:event_cbClientesActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(cbClientes.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Selecione um Cliente!");
        }else{
            try {
                cli = new Cliente();
                selecionaIdsCliente();
                
                cli.setIdCliente(cli.getIdCliente());
                
                cliDAO = new ClienteDAO();
                cliDAO.pesquisar(cli);

                txtNome.setText(cli.getNomeCliente());
                txtSobreNome.setText(cli.getSobreNomeCliente());
                txtCpf.setText(cli.getCpfCliente());
            } catch (Exception ex) {
                Logger.getLogger(CadastroClientesGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         if(cbClientes.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um cliente");
        }else{    
        //selecionaIdsCliente();
        //Decidir em usar variavel temporaria ou nao
        //int idClienteTemp = cli.getIdCliente();
            
        try {
             if("".equals(txtNome.getText()) || "".equals("".equals(txtSobreNome.getText())) || "".equals(txtCpf.getText())){
            JOptionPane.showMessageDialog(null,"Campo de Cliente vazio!");
             }else{
            
                 
            cli = new Cliente();
            selecionaIdsCliente();
            //Ainda decidir de usar variavel Temporaria ou nao
            System.out.println("" + cli.getIdCliente());
            cliDAO = new ClienteDAO();
                
            //rece.setIdReceita(idReceitaTemp); 
            cli.setIdCliente(cli.getIdCliente());
            cli.setNomeCliente(txtNome.getText());
            cli.setSobreNomeCliente(txtSobreNome.getText());
            cli.setCpfCliente(txtCpf.getText());
                // System.out.println("" + prod.getIdProduto());
            //rece.setNomeReceita(txtReceita.getText());
            //receDAO.atualizar(rece);
            cliDAO.atualizar(cli);
            
            JOptionPane.showMessageDialog(null,"Cliente Alterado com sucesso!");
            inicializaComboCliente();
            }
             
        } catch (Exception ex) {
            Logger.getLogger(CadastroReceitaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpaCampos();
         
      }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(cbClientes.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um Cliente!!");
        }else{
        cli = new Cliente();
        try {
            cliDAO = new ClienteDAO();
            selecionaIdsCliente();
            int opcao =  JOptionPane.showConfirmDialog(null,"Pode haver uma Venda com esse cliente deseja excluir realmente ?");
                if(opcao == 0){
            cli.setIdCliente(cli.getIdCliente());
            cliDAO.excluir(cli);
            JOptionPane.showMessageDialog(null,"Cliente Excluido com Sucesso!!");
            inicializaComboCliente();
            }
 
            
        } catch (Exception ex) {
            Logger.getLogger(CadastroClientesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_btnExcluirActionPerformed
 public final void inicializaComboCliente() throws Exception {
        DefaultComboBoxModel comboCliente = new DefaultComboBoxModel();
        comboCliente.addElement("Selecione Cliente");
        cliDAO = new ClienteDAO();
        cli = new Cliente();
        clientes = cliDAO.listaTodosClientes(cli);
        for (Cliente c : clientes) {
            comboCliente.addElement(c.getNomeCliente() + " " + c.getSobreNomeCliente());
        }
        cbClientes.setModel(comboCliente);
        //decidir se vai setar 0 ou nao
        //cbClientes.setSelectedIndex(0);
    }
 private void selecionaIdsCliente(){
     int ind = cbClientes.getSelectedIndex();
        if (ind < 1) {
            cli = null;
            return;
        }
        ind--;
        cli = clientes.get(ind);
        //System.out.println(rece.getIdReceita());
    }
 public void limpaCampos(){
     txtNome.setText("");
     txtSobreNome.setText("");
     txtCpf.setText("");
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new CadastroClientesGUI().setVisible(true);
//                CadastroClientesGUI cadastroClientesGUI = new CadastroClientesGUI();
//                try {
//                    cadastroClientesGUI.
//                    cadastroClientesGUI.setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(CadastroClientesGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCad;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobreNome;
    // End of variables declaration//GEN-END:variables
}
