/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProdutoDAO;
import dao.ReceitaDAO;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import model.Produto;
import model.Receita;
import util.ValidaNumeros;


/**
 *
 * @author Daniel Lima
 */
public class CadastroProdutoGUI extends javax.swing.JFrame {
    Produto prod;
    ProdutoDAO prodDAO;
    Receita rece;
    ReceitaDAO receDAO;
    private List<Receita> receitas = new ArrayList<>();
    private List<Produto> produtos = new ArrayList<>();
    private List<Produto> idProdutos = new ArrayList<>();
    static int idReceitaTemp;
    /**
     * Creates new form CadastroProdutoGUI
     */
    public CadastroProdutoGUI() throws Exception {
        initComponents();
        inicializaComboProduto();
        inicializaComboReceita();
    //txtPreco.setDocument(new ValidaNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbProduto = new javax.swing.JComboBox<>();
        lblProdutos = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblReceita = new javax.swing.JLabel();
        cbReceita = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        atu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Produtos"));

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Produto" }));
        cbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutoActionPerformed(evt);
            }
        });

        lblProdutos.setText("Produtos");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutos)
                .addGap(29, 29, 29)
                .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdutos)
                    .addComponent(btnBuscar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Produtos"));

        lblNome.setText("Nome");

        lblPreco.setText("Preço");

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        txtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoFocusLost(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblReceita.setText("Receita");

        cbReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Receita" }));
        cbReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReceitaActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        atu.setText("Atualizar");
        atu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addGap(14, 14, 14)
                                .addComponent(btnLimpar))
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblReceita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbReceita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atu)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceita)
                    .addComponent(cbReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
          if(cbProduto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um produto");
        }else{    
        selecionaIds();
        //idReceitaTemp = rece.getIdReceita();
        int idProdutoTemp = prod.getIdProduto();
            
        try {
             if("".equals(txtNomeProduto.getText()) || "".equals(txtPreco.getText())){
            JOptionPane.showMessageDialog(null,"Campo de receita vazio!");
             }else{
            rece = new Receita();
            prod = new Produto();
            
            prodDAO = new ProdutoDAO();
                
            //rece.setIdReceita(idReceitaTemp); 
            prod.setIdProduto(idProdutoTemp);
            prod.setNomeProduto(txtNomeProduto.getText());
            prod.setPrecoProduto(Double.parseDouble(txtPreco.getText()));
            
                // System.out.println("" + prod.getIdProduto());
            //rece.setNomeReceita(txtReceita.getText());
            //receDAO.atualizar(rece);
            prodDAO.atualizar(prod);
            
            JOptionPane.showMessageDialog(null,"Produto Alterado com sucesso!");
            inicializaComboProduto();
            }
             
        } catch (Exception ex) {
            Logger.getLogger(CadastroReceitaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomeProduto.setText("");
        txtPreco.setText("");
         
      }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       if(cbProduto.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(null,"Selecione um Produto!");
        }else{
        
           try {
               int opcao =  JOptionPane.showConfirmDialog(null,"Pode haver uma venda com esse produto deseja excluir ?");
               //System.out.println(opcao);
                    if(opcao == 0){
               prod = new Produto();
               prod.setNomeProduto(cbProduto.getSelectedItem().toString());
               prodDAO = new ProdutoDAO();
               prodDAO.excluir(prod);
               JOptionPane.showMessageDialog(null,"Produto Excluido com Sucesso");
               inicializaComboProduto();
                    }
               
           } catch (Exception ex) {
               Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
       
       }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        String nome =  txtNomeProduto.getText();
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
       Double preco = Double.parseDouble(txtPreco.getText());
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
             if(cbReceita.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione alguma Receita!!");
            
            }else{
            prod = new Produto();
            rece = new Receita();
             if("".equals(txtNomeProduto.getText()) || "".equals(txtPreco.getText())){
                JOptionPane.showMessageDialog(null,"Campo Vazio");  
             }else{
            prod.setNomeProduto(txtNomeProduto.getText());
            prod.setPrecoProduto(Double.parseDouble(txtPreco.getText()));
        try {
            prodDAO = new ProdutoDAO();
            // aki eu seto os ids de acordo com os ids do banco para salvar como chave estrangeira//
            selecionaIds();
            //System.out.println("" + rece.getIdReceita());
            
            prodDAO.cadastrarProduto(prod,rece.getIdReceita());
            JOptionPane.showMessageDialog(null,"Produto Cadastrado com sucesso!");  
            inicializaComboProduto();
            txtNomeProduto.setText("");
            txtPreco.setText("");
        } catch (Exception ex) {
            Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
       }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReceitaActionPerformed
        selecionaIds();   
    }//GEN-LAST:event_cbReceitaActionPerformed

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed
            selecionaIdsProduto();  
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(cbProduto.getSelectedIndex() == 0){
          JOptionPane.showMessageDialog(null,"Selecione um produto ");
        }else{
        try {
            prod = new Produto();
            selecionaIdsProduto();            
            prodDAO = new ProdutoDAO();
            prodDAO.pesquisar(prod);
           
            
            txtNomeProduto.setText(prod.getNomeProduto());
            txtPreco.setText(prod.getPrecoProduto().toString());
        } catch (Exception ex) {
            Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoFocusLost
        
    }//GEN-LAST:event_txtPrecoFocusLost

    private void atuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atuActionPerformed
        try {
            inicializaComboReceita();
        } catch (Exception ex) {
            Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atuActionPerformed
    public final void inicializaComboReceita() throws Exception {
        DefaultComboBoxModel comboReceita = new DefaultComboBoxModel();
        comboReceita.addElement("Selecione Receita");
        receDAO = new ReceitaDAO();
        rece = new Receita();
        receitas = receDAO.listaTodasReceitas(rece);
        for (Receita r : receitas) {
            comboReceita.addElement(r.getNomeReceita());
        }
        cbReceita.setModel(comboReceita);
        //cbReceita.setSelectedIndex(0);
    }
     public final void inicializaComboProduto() throws Exception {
        DefaultComboBoxModel comboProduto = new DefaultComboBoxModel();
        comboProduto.addElement("Selecione Produto");
        prodDAO = new ProdutoDAO();
        prod = new Produto();
        produtos = prodDAO.listaTodosProdutos(prod);
        for (Produto p : produtos) {
            comboProduto.addElement(p.getNomeProduto());
        }
        cbProduto.setModel(comboProduto);
        //decidir se vai setar 0 ou nao
        //cbProduto.setSelectedIndex(0);
    }
    private void selecionaIds(){
     int ind = cbReceita.getSelectedIndex();
        if (ind < 1) {
            rece = null;
            return;
        }
        ind--;
        rece = receitas.get(ind);
        
    }
     private void selecionaIdsProduto(){
     int ind = cbProduto.getSelectedIndex();
        if (ind < 1) {
            rece = null;
            return;
        }
        ind--;
        prod = produtos.get(ind);
        
    }
     public void limparCampos(){
        txtNomeProduto.setText("");
        txtPreco.setText("");
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               CadastroProdutoGUI cadastroProdutoGUI = new CadastroProdutoGUI();
//               cadastroProdutoGUI.setVisible(true);
//                try {
//                    cadastroProdutoGUI.inicializaComboProduto();
//                    cadastroProdutoGUI.inicializaComboReceita();
//                } catch (Exception ex) {
//                    Logger.getLogger(CadastroProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atu;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JComboBox<String> cbReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblReceita;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
