/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProdutoDAO;
import dao.ProdutoDaVendaDAO;
import dao.VendaDAO;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Produto;
import model.ProdutoHasVenda;
import model.ProdutoVendaTableModel;
import model.Venda;
import util.Data.ValidaData;

/**
 *
 * @author Daniel Lima
 */
public class ListaProdutosProducaoGUI extends javax.swing.JFrame {
    Produto prod;
    ProdutoDAO prodDAO;
    ProdutoHasVenda pV;
    ProdutoDaVendaDAO pvDAO;
    Venda vend ;
    VendaDAO vendDAO ;
    private List<ProdutoHasVenda> produtoQtd = new ArrayList<>();
    private List<Produto> produtos = new ArrayList<>();
    private List<Venda> vendas = new ArrayList<>();
    /**
     * Creates new form ListaProdutosProduçao
     */
    public ListaProdutosProducaoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        lblConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        lblProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Produtos em Produçao");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lblData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblData.setText("Data");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });

        lblConsulta.setText("Consulta");
        lblConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblConsultaActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ProdutoVendaTableModel modelo = new ProdutoVendaTableModel();
        tabelaProdutos.setModel(modelo);
        jScrollPane1.setViewportView(tabelaProdutos);

        lblProduto.setText("Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(lblConsulta)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblConsultaActionPerformed
        if(txtData.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null,"Campo vazio!");
        }else{
        populaTable();
        }
    }//GEN-LAST:event_lblConsultaActionPerformed

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
        if(!txtData.getText().equals("  /  /    ")){
              if(!ValidaData.validaData(txtData.getText())){
                  JOptionPane.showMessageDialog(null,"Data invalida");
                  txtData.setText("");
                  txtData.requestFocus();
                //  System.out.println("" + txtDataValidade.getText()); 
              }
           }
    }//GEN-LAST:event_txtDataFocusLost
    public void populaTable(){
        limparProdTable();
        prod = new Produto();
        pV = new ProdutoHasVenda();
        vend = new Venda();
        
        try {
            
            ProdutoVendaTableModel modelo = (ProdutoVendaTableModel) tabelaProdutos.getModel();
            
            SimpleDateFormat formatdata = new SimpleDateFormat("dd/MM/yyyy"); 
    
            Date dataConsulta = new Date (formatdata.parse(txtData.getText()).getTime());
            
            prodDAO = new ProdutoDAO();
            produtos = prodDAO.listaDadosVendaDataFixa(dataConsulta);
            pvDAO = new ProdutoDaVendaDAO();
            produtoQtd = pvDAO.listaQntdProdutoProducao(dataConsulta);
            if(produtos.size() == 0)
                JOptionPane.showMessageDialog(null,"Nao existem produtos nessa data");
                
            for(int i =0 ;i < produtos.size() ; i++){
               prod.setIdProduto(produtos.get(i).getIdProduto());
               prod.setNomeProduto(produtos.get(i).getNomeProduto());
               prod.setPrecoProduto(produtos.get(i).getPrecoProduto());
               pV.setQtdPrdVenda(produtoQtd.get(i).getQtdPrdVenda());
               
               modelo.addRow(new Produto(prod.getIdProduto(),prod.getNomeProduto(),prod.getPrecoProduto()),new ProdutoHasVenda(pV.getQtdPrdVenda()));
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ListaProdutosProducaoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    public void limpaCampos(){
        txtData.setText("");
    }
    public void limparProdTable() {
        ProdutoVendaTableModel modelo = (ProdutoVendaTableModel)tabelaProdutos.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosProducaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosProducaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosProducaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProdutosProducaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaProdutosProducao().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaProdutosProducao().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblConsulta;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JFormattedTextField txtData;
    // End of variables declaration//GEN-END:variables
}
