/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClienteDAO;
import dao.ProdutoDAO;
import dao.ProdutoDaVendaDAO;
import dao.VendaDAO;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Produto;
import model.ProdutoHasVenda;
import model.ProdutoVendaTableModel;
import model.Venda;
import model.VendasPeriodoTableModel;
import util.Data.ValidaData;

/**
 *
 * @author Daniel Lima
 */
public class ListarVendasPeriodoGUI extends javax.swing.JFrame {
    Venda vend;
    Cliente cli;
    VendaDAO vendDAO;
    ClienteDAO cliDAO;
    ProdutoHasVenda pV;
    ProdutoDaVendaDAO pvDAO;
    Produto prod;
    ProdutoDAO prodDAO;
    private List<Produto> produtos = new ArrayList<>();
    private List<ProdutoHasVenda> produtoVenda = new ArrayList<>();
    private List<Venda> vendas = new ArrayList<>();
    private List<Venda> vendasCalc = new ArrayList<>();
    private List<Cliente> clientes = new ArrayList<>();
    /**
     * Creates new form ListarVendasPeriodo
     */
    public ListarVendasPeriodoGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblDataInicio = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendasPeriodo = new javax.swing.JTable();
        lblDataFim = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        txtDataFim = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        lblProdutos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Vendas Por Periodo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        lblDataInicio.setText("Data Inicio");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tabelaVendasPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        VendasPeriodoTableModel modelo = new VendasPeriodoTableModel();
        tabelaVendasPeriodo.setModel(modelo);
        tabelaVendasPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendasPeriodoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVendasPeriodo);

        lblDataFim.setText("Data Fim");

        try {
            txtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioActionPerformed(evt);
            }
        });

        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFimFocusLost(evt);
            }
        });

        jLabel1.setText("a");

        lblVendas.setText("Vendas");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ProdutoVendaTableModel modelo2 = new ProdutoVendaTableModel();
        tabelaProdutos.setModel(modelo2);
        jScrollPane2.setViewportView(tabelaProdutos);

        lblProdutos.setText("Produtos");

        jLabel2.setText("Total em Dinheiro no Período");

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDataInicio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblDataFim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblVendas)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(lblProdutos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicio)
                    .addComponent(lblDataFim)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addGap(4, 4, 4)
                .addComponent(lblVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        
        if(txtDataInicio.getText().equals("  /  /    ") || txtDataFim.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null,"Campo de data vazio !!");
        }else{
            try {
            txtTotal.setText("" + calculaTotalPeriodo());
        } catch (Exception ex) {
            Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
      limparVendaTable();
      populaTable();
        }
    }//GEN-LAST:event_btnListarActionPerformed
    public void limparVendaTable() {
        VendasPeriodoTableModel modelo = (VendasPeriodoTableModel)tabelaVendasPeriodo.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
}
}
    public void limparProdTable() {
        ProdutoVendaTableModel modelo2 = (ProdutoVendaTableModel) tabelaProdutos.getModel();
        while (modelo2.getRowCount() > 0) {
            modelo2.removeRow(0);
}
}
    public void populaTable(){
        try {
            
            vendDAO = new VendaDAO();
            vend = new Venda();
            cli = new Cliente();
            VendasPeriodoTableModel modelo = (VendasPeriodoTableModel)tabelaVendasPeriodo.getModel();
            SimpleDateFormat formatdata = new SimpleDateFormat("dd/MM/yyyy"); 
    
            Date dataIniTemp = new Date (formatdata.parse(txtDataInicio.getText()).getTime());
            Date dataFimTemp = new Date (formatdata.parse(txtDataFim.getText()).getTime());
  
            vendas = vendDAO.listaVendaPeriodo(dataIniTemp,dataFimTemp);
            if(vendas.size() == 0){
                JOptionPane.showMessageDialog(null,"Nenhumas Venda com status pronto Realizada nesse Período!");
            }
            for(Venda v: vendas){
                cliDAO = new ClienteDAO();
                clientes = cliDAO.consultaClienteID(v.getIdCliente());
                
                vend.setIdVendas(v.getIdVendas());
                vend.setDataVendas(v.getDataVendas());
                
                for(Cliente c: clientes){
                    
                    cli.setNomeCliente(c.getNomeCliente());
                    
                    modelo.addRow(new Venda(vend.getIdVendas(),vend.getDataVendas()),new Cliente(cli.getNomeCliente()));
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    private void txtDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioActionPerformed
       if(!txtDataInicio.getText().equals("  /  /    ")){
              if(!ValidaData.validaData(txtDataInicio.getText())){
                  JOptionPane.showMessageDialog(null,"Data invalida");
                  txtDataInicio.setText("");
                  txtDataInicio.requestFocus();
                //  System.out.println("" + txtDataValidade.getText()); 
              }
           }
    }//GEN-LAST:event_txtDataInicioActionPerformed

    private void tabelaVendasPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendasPeriodoMouseClicked
        limparProdTable();
        vend = new Venda();
        prod = new Produto();
        pV = new ProdutoHasVenda();
        int linha = tabelaVendasPeriodo.getSelectedRow();
        
//        ProdutoVendaTableModel modelo = (ProdutoVendaTableModel) tabelaProdutos.getModel();
        
        try {
            VendasPeriodoTableModel modelo = (VendasPeriodoTableModel)tabelaVendasPeriodo.getModel();
        
            vend.setIdVendas(Integer.parseInt(modelo.getValueAt(linha,0).toString()));
        
            pvDAO = new ProdutoDaVendaDAO();
            prodDAO = new ProdutoDAO();
            
            produtos = prodDAO.listaDadosProdPeloID(vend.getIdVendas());
            
            if(produtos.size() == 0){
                JOptionPane.showMessageDialog(null,"Nenhum produto nessa venda");
            }
            produtoVenda = pvDAO.listaQntdProduto(vend.getIdVendas());
            
            ProdutoVendaTableModel modelo2 = (ProdutoVendaTableModel) tabelaProdutos.getModel();
            
            for(int i=0 ; i < produtos.size() ; i++){
                
                prod.setIdProduto(produtos.get(i).getIdProduto());
                prod.setNomeProduto(produtos.get(i).getNomeProduto());
                prod.setPrecoProduto(produtos.get(i).getPrecoProduto());
                pV.setQtdPrdVenda(produtoVenda.get(i).getQtdPrdVenda());
                
                modelo2.addRow(new Produto(prod.getIdProduto(),prod.getNomeProduto(),prod.getPrecoProduto()), new ProdutoHasVenda(pV.getQtdPrdVenda()));
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaVendasPeriodoMouseClicked

    private void txtDataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFimFocusLost
        if(!txtDataFim.getText().equals("  /  /    ")){
              if(!ValidaData.validaData(txtDataFim.getText())){
                  JOptionPane.showMessageDialog(null,"Data invalida");
                  txtDataFim.setText("");
                  txtDataFim.requestFocus();
                //  System.out.println("" + txtDataValidade.getText()); 
              }
           }
    }//GEN-LAST:event_txtDataFimFocusLost

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        
    }//GEN-LAST:event_txtTotalActionPerformed
    private double calculaTotalPeriodo() throws Exception{
        vend = new Venda();
        
        double tempTotal = 0;
                
        prod = new Produto();
        
        SimpleDateFormat formatdata = new SimpleDateFormat("dd/MM/yyyy");
        
        Date dataIniTemp = new Date (formatdata.parse(txtDataInicio.getText()).getTime());
        Date dataFimTemp = new Date (formatdata.parse(txtDataFim.getText()).getTime());
        
        vendDAO = new VendaDAO();
        vendasCalc = vendDAO.listaVendaPeriodo(dataIniTemp,dataFimTemp);
        
        
        for(Venda v: vendasCalc){
            
            prodDAO = new ProdutoDAO();
            produtos = prodDAO.listaDadosProdPeloID(v.getIdVendas());
            pvDAO = new ProdutoDaVendaDAO();
            produtoVenda = pvDAO.listaQntdProduto(v.getIdVendas());
            for(Produto p: produtos){
                
                for(ProdutoHasVenda pV: produtoVenda){
//                    System.out.println(p.getNomeProduto() + " " + p.getPrecoProduto());
//                    System.out.println(pV.getQtdPrdVenda());
                    tempTotal = tempTotal + p.getPrecoProduto() * pV.getQtdPrdVenda();
                }
            }
        }
//            prodDAO = new ProdutoDAO();
            
//            
          
        return tempTotal;
    }

    public void limpaCampos(){
        txtDataInicio.setText("");
        txtDataFim.setText("");
        txtTotal.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarVendasPeriodoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListarVendasPeriodoGUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tabelaVendasPeriodo;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
